[tool.blue]
line-length = 79

[tool.isort]
profile = "black"
known_django_party = ["api_yamdb"]
known_local_folder = ["api", "rewiews", "users"]
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'FIRSTPARTY', 'DJANGO_PARTY', 'LOCALFOLDER']
line_length = 79