# Generated by Django 3.2 on 2023-06-06 18:30

import django.core.validators
import django.db.models.deletion
import reviews.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Введите категорию произведения',
                        max_length=256,
                        verbose_name='Категория',
                    ),
                ),
                (
                    'slug',
                    models.SlugField(
                        help_text='Введите группу категории произведения',
                        unique=True,
                        verbose_name='Группа',
                    ),
                ),
            ],
            options={
                'verbose_name': 'категорию',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('text', models.TextField(verbose_name='Текст комментария')),
                (
                    'pub_date',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата комментария'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ('pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Введите жанр произведения',
                        max_length=256,
                        verbose_name='Жанр',
                    ),
                ),
                (
                    'slug',
                    models.SlugField(
                        help_text='Введите группу жанра произведения',
                        unique=True,
                        verbose_name='Группа',
                    ),
                ),
            ],
            options={
                'verbose_name': 'жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                (
                    'score',
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(10),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name='Оценка',
                    ),
                ),
                (
                    'pub_date',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата отзыва'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ('pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Введите название произведения',
                        max_length=256,
                        verbose_name='Название',
                    ),
                ),
                (
                    'year',
                    models.PositiveSmallIntegerField(
                        help_text='Введите дату выхода произведения',
                        validators=[reviews.validators.validate_year],
                        verbose_name='Дата выхода',
                    ),
                ),
                (
                    'description',
                    models.TextField(
                        blank=True,
                        help_text='Введите описание произведения',
                        verbose_name='Описание',
                    ),
                ),
                (
                    'category',
                    models.ForeignKey(
                        help_text='Выберите категорию произведения',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='reviews.category',
                        verbose_name='Категория',
                    ),
                ),
            ],
            options={
                'verbose_name': 'произведение',
                'verbose_name_plural': 'Произведения',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='TitleGenre',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'genre',
                    models.ForeignKey(
                        help_text='Выберите жанр',
                        on_delete=django.db.models.deletion.CASCADE,
                        to='reviews.genre',
                        verbose_name='Жанр',
                    ),
                ),
                (
                    'title',
                    models.ForeignKey(
                        help_text='Выберите произведение',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='reviews.title',
                        verbose_name='Произведение',
                    ),
                ),
            ],
            options={
                'verbose_name': 'произведение и жанр',
                'verbose_name_plural': 'Произведения и жанры',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(
                help_text='Выберите жанр произведения',
                through='reviews.TitleGenre',
                to='reviews.Genre',
                verbose_name='Жанр',
            ),
        ),
    ]
